### ISSUE TITLE
建议部署到github page

### ISSUE THREAD

**Issue by ArchGeass** [mrbulb/ONEPIECE-KG#1]
若您没有搭建个人技术博客的意向，建议将此项目部署到您的仓库对应***github page***上，然后分享相应链接，这样方便大家直观的**查阅效果**，项目**永久存在**，也方便**更新迭代**。
若您愿意采纳建议，在实施阶段若遇到困难，可以进一步探讨解决。

**Comment by mrbulb** [comment]
哇，好的，非常感谢你的建议。因为没有系统学过网页部分知识来着，只是选择网页做可视化的展示方式。刚刚看了一下github page貌似不用搞服务器，也不耗流量来着，还是很方便的，之后有空的话我部署一下。到时候如果部署时遇到什么问题，再向您请教一下

**Comment by mrbulb** [comment]
@ArchGeass 您好，我已经将可视化页面部署到GitHub Pages上了，链接地址是：https://mrbulb.github.io/ONEPIECE-KG/
感谢您的建议 :smile:

**Comment by ArchGeass** [comment]
![2020-02-29 22-45-32 的屏幕截图](https://user-images.githubusercontent.com/16267662/75609632-49f6bf00-5b45-11ea-8f00-4b7a94286d4f.png)
您好，我这边看到的效果与论坛上的截图不同呢，已使用不同的浏览器去测试，均如截图所示

**Comment by ArchGeass** [comment]
现在刷新可以看到效果了。
有办法在点击一个元素的时候，暂时隐藏其他无关元素么？目前是鼠标一旦离开就失去隐藏效果。

我觉得这个项目可以加大宣传，让更多(有能力有意向)人来提交**PR**，成为国内海贼圈的一个里程碑作品，哈哈~

**Comment by mrbulb** [comment]
> 现在刷新可以看到效果了。
> 有办法在点击一个元素的时候，暂时隐藏其他无关元素么？目前是鼠标一旦离开就失去隐藏效果。
> 
> 我觉得这个项目可以加大宣传，让更多(有能力有意向)人来提交**PR**，成为国内海贼圈的一个里程碑作品，哈哈~

如果想要隐藏别的元素的话，可以在左边的搜索框里面输入角色的名字，这时候把鼠标放在上面，离开后就不会失去隐藏的结果。
当时设计的时候也有考虑过你说的那种实现方式，但是我想大多数人可能一进来可能想多看看几个不同的角色，而不是暂时focus在某个角色里面，所以就把这个特色放在搜索框的结果里面，而不是一进来的页面中。
至于宣传的话，因为是课程项目，用到talkop整理的数据，所以做完之后就先发到论坛那边，也算是回馈社区了。其他的一些宣传途径我也不大知道来着，如果您要是觉得不错的话，也欢迎向周围的人安利一下，大家一起把这个项目做的更好:smile:
