### ISSUE TITLE
可视化中关系只表示为连接没有具体关系类型

### ISSUE THREAD

**Issue by ngl567** [mrbulb/ONEPIECE-KG#3]
非常感谢开源这个很不错的项目，我也很喜欢海贼王，请问在可视化中实体之间的关系只表现为连接，而没有具体的关系类型表示，请问具体的关系能否添加在可视化中，谢谢。

**Comment by mrbulb** [comment]
感谢对真个项目的认可:smile:
关系类型的添加已经在开发计划中了，但因为最近上课就没来得及搞，应该下个版本里面会有，如果着急看的话，也可以导入neo4j里面查看，方法在项目文档里面有，效果大概如下图所示
![graph (3)](https://user-images.githubusercontent.com/30287341/76771961-17062980-67db-11ea-9e6f-5bf17950ea84.png)
还有就是因为本身结点之间的连线就有些密集，再加上关系类型之后会更加密，不知道你在可视化展示那边有没有一些建议

**Comment by ngl567** [comment]
感谢解答，neo4j可视化也不错，你给出的D3可视化效果更好，不知是否可以设置在选中一个实体结点时显示出相关的其它实体及之间的关系类型，这样显示效果应该不会太过密集。

**Comment by mrbulb** [comment]
嗯嗯，在选中时显示这个方案应该不错，感谢你的建议，我会在之后更新一下

**Comment by ngl567** [comment]
请教一下，在CHANGELOG中看到有实体对齐操作，请问可视化部分如何进行的关系数据实体对齐？

**Comment by mrbulb** [comment]
@ngl567 更新了一下代码，现在应该可以看到关系显示了

**Comment by ngl567** [comment]
很棒啊，多谢学习到了。

**Comment by mrbulb** [comment]
> 请教一下，在CHANGELOG中看到有实体对齐操作，请问可视化部分如何进行的关系数据实体对齐？

因为原始数据实体的mention可能有多个，这个对齐只是了让可视化效果看起来不那么乱，所以只是非常简单的构造了一个[映射表](https://github.com/mrbulb/ONEPIECE-KG/blob/master/deepke-master/data/vivrecard/alignment/raw_entity_mapping.txt)，构建的方式也非常简单，就是基于字符串相似度的初步筛选+人工修正，没有用到复杂的技术

这部分也有专门的研究内容，一些比较高级的技术可以参见这篇文章：https://blog.csdn.net/u012736685/article/details/100184414

**Comment by ngl567** [comment]
好的，非常感谢。

**Comment by mrbulb** [comment]
@ngl567 对了老哥，你那边开发的时候，可以把 `index.html` 里面的下面这段代码给删掉来着，因为这个是关联着我的网站统计信息的接口来着

    <script>
            var _hmt = _hmt || [];
            (function() {
                var hm = document.createElement("script");
                hm.src = "https://hm.baidu.com/hm.js?464c614e438da7785d1dbd393096c677";
                var s = document.getElementsByTagName("script")[0]; 
                s.parentNode.insertBefore(hm, s);
            })();
        </script>

**Comment by ngl567** [comment]
感谢提醒，已经处理了。
