### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by pandaao** [mrbulb/ONEPIECE-KG#4]
请问raw_moegirl_onepiece_entries.txt中的原始数据，在萌娘百科中具体是怎么获取的？

**Comment by mrbulb** [comment]
您好，我印象中是从这边获取的：https://zh.moegirl.org.cn/index.php?title=Template:%E6%B5%B7%E8%B4%BC%E7%8E%8B&action=edit
具体可以参考一下项目文档，里面有相关链接信息；https://github.com/mrbulb/ONEPIECE-KG/blob/master/docs/report.md#321-%E6%8A%BD%E5%8F%96%E9%80%9A%E7%94%A8%E7%9F%A5%E8%AF%86%E5%9B%BE%E8%B0%B1%E4%B8%AD%E5%B7%B2%E6%9C%89%E7%9A%84%E7%9B%AE%E6%A0%87%E5%9F%9F%E7%9F%A5%E8%AF%86
